#This file was originally generated by PyScripter's unitest wizard

import unittest
import MaxWordSegmentation

class TestGlobalFunctions(unittest.TestCase):

    def testload_dict(self):
        filename = 'dict.txt'
        print("input filename",filename)
        strList,maxLen = MaxWordSegmentation.load_dict(filename)
        print("max length is",maxLen)

    def testsegmentation(self):
        pass

if __name__ == '__main__':
    unittest.main()