all: preprocess count-char generate-map test gen-context stats

preprocess: preprocess.cpp
	g++ -o preprocess preprocess.cpp

count-char: count-char.cpp
	g++ -o count-char count-char.cpp

generate-map: generate-map.cpp
	g++ -o generate-map generate-map.cpp

test: test.cpp
	g++ -o test test.cpp

gen-context: gen-context.cpp
	g++ -o gen-context gen-context.cpp

stats: stats.cpp
	g++ -o stats stats.cpp
